apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  tasks:
    - name: pipeline-hunter-task
      taskRef:
        name: hunter-task
      workspaces:
        - name: task-pvc
          workspace: pipeline-pvc
  workspaces:
    - name: pipeline-pvc
