apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  tasks:
    - name: pipeline-hunter-task-amd64
      taskRef:
        name: hunter-task-amd64
    - name: pipeline-hunter-task
      taskRef:
        name: hunter-task-s390
