apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  tasks:
    - name: pipeline-hunter-task-amd64
      taskRef:
        name: hunter-task
    - name: pipeline-hunter-task-s390x
      taskRef:
        name: hunter-task
