apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  tasks:
    - name: pipeline-hunter-task-amd64
      taskRef:
        name: hunter-task-amd64
      workspaces:
        - name: task-pvc
          workspace: pipeline-pvc
    - name: pipeline-hunter-task
      taskRef:
        name: hunter-task-s390
  workspaces:
    - name: pipeline-pvc
