apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hunter-task
spec:
  steps:
  - name: check-kata-privileged
    securityContext:
      privileged: true
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - df;
      ls -al /dev;
      ls -alR /var/run/secrets
  - name: kube-hunter
    image: aquasec/kube-hunter 
    command: ["python", "kube-hunter.py"]
    workingDir: /kube-hunter
    args: ["--pod"]