apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hunter-task
spec:
  steps:
  - name: check-unprivileged
    securityContext:
      privileged: false
    image: registry.access.redhat.com/ubi8
    command: ["/bin/sh", "-c"]
    args:
    - uname -a;
      whoami;
      pwd;
      ls -al;
      df -Th;
      ls -al /dev;
      ls -alR /var/run/secrets;
  - name: check-privileged
    securityContext:
      privileged: true
    image: registry.access.redhat.com/ubi8
    command: ["/bin/sh", "-c"]
    args:
    - uname -a;
      whoami;
      pwd;
      ls -al;
      df -Th;
      ls -al /dev;
      ls -alR /var/run/secrets;

