apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hunter-task
  annotations:
    io.kubernetes.cri.untrusted-workload: "false"
spec:
  steps:
  - name: check-kata-privileged
    securityContext:
      privileged: true
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - df -Th;
      uname -a;
      ls -al /dev;
      ls -alR /var/run/secrets;
      apt-get update;
  - name: kube-hunter
    image: aquasec/kube-hunter
    command: ["kube-hunter"]
    args: ["--pod"]
