apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hunter-task-amd64
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: arch
              operator: In
              values:
              - amd64
  steps:
  - name: check-kata-unprivileged
    securityContext:
      privileged: false
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - pwd;
      ls -al;
      df -Th;
      uname -a;
      ls -al /dev;
      ls -alR /var/run/secrets;
      apt-get update;
      whoami;
  - name: check-kata-privileged
    securityContext:
      privileged: true
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - df -Th;
      uname -a;
      ls -al /dev;
      ls -alR /var/run/secrets;
      apt-get update;
      whoami;
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hunter-task-s390
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: arch
              operator: In
              values:
              - s390
  steps:
  - name: check-kata-unprivileged
    securityContext:
      privileged: false
    image: registry.access.redhat.com/ubi8
    command: ["/bin/sh", "-c"]
    args:
    - pwd;
      ls -al;
      df -Th;
      uname -a;
      ls -al /dev;
      ls -alR /var/run/secrets;
      whoami;
  - name: check-kata-privileged
    securityContext:
      privileged: true
    image: registry.access.redhat.com/ubi8
    command: ["/bin/sh", "-c"]
    args:
    - df -Th;
      uname -a;
      ls -al /dev;
      ls -alR /var/run/secrets;
      whoami;

