apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hunter-task
spec: 
  steps:
  - name: kube-hunter
    image: aquasec/kube-hunter 
    command: ["python", "/kube-hunter.py"]
    args: ["--pod"]