apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hunter-task
spec:
  steps:
  - name: check-kata-unprivileged
    securityContext:
      privileged: false
    image: ubuntu
    script: |
      set -o errexit;
      set -x;
      while true; do free -m | awk "NR==2{printf \"[Memory: %.2f%%, \", \$3*100/\$2 }"; df -h | awk '$NF=="/"{printf "Disk: %s]\n", $5}'; sleep 30; done &;
      pwd;
      ls -al;
      df -Th;
      uname -a;
      ls -al /dev;
      ls -alR /var/run/secrets;
      whoami;
      mkdir /artifacts/test;
      rmdir /artifacts/test;
      apt update;
      apt install curl tar xz-utils -y;
      cd ~;
      time curl -Ls -O https://github.com/kata-containers/kata-containers/releases/download/3.2.0/kata-static-3.2.0-amd64.tar.xz;
      time tar xJ -f ~/kata-static-3.2.0-amd64.tar.xz;
      cd /artifacts;
      time tar xJ -f ~/kata-static-3.2.0-amd64.tar.xz;
    workingDir: $(workspaces.task-pvc.path)
  - name: check-kata-privileged
    securityContext:
      privileged: true
    image: ubuntu
    command: ["/bin/bash", "-c"]
    args:
    - df -Th;
      uname -a;
      ls -al /dev;
      ls -alR /var/run/secrets;
      apt-get update;
      whoami;
      mkdir /artifacts/test;
      rmdir /artifacts/test;
      apt update;
      apt install curl tar xz-utils -y;
      cd ~;
      time curl -Ls -O https://github.com/kata-containers/kata-containers/releases/download/3.2.0/kata-static-3.2.0-amd64.tar.xz;
      time tar xJ -f ~/kata-static-3.2.0-amd64.tar.xz;
      cd /artifacts;
      time tar xJ -f ~/kata-static-3.2.0-amd64.tar.xz;      
    workingDir: $(workspaces.task-pvc.path)
  - name: kube-hunter
    image: aquasec/kube-hunter:0.5.0
    command: ["kube-hunter"]
    args: ["--pod"]
    workingDir: $(workspaces.task-pvc.path)
  workspaces:
  - name: task-pvc
    mountPath: /artifacts
