apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hunter-task
spec:
  steps:
  - name: check-kata-unprivileged
    securityContext:
      privileged: false
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - pwd;
      ls -al;
      df -Th;
      uname -a;
      ls -al /dev;
      ls -alR /var/run/secrets;
      apt-get update;
      whoami;
      mkdir /artifacts/test;
      rmdir /artifacts/test;
    workingDir: $(workspaces.task-pvc.path)
  - name: check-kata-privileged
    securityContext:
      privileged: true
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - df -Th;
      uname -a;
      ls -al /dev;
      ls -alR /var/run/secrets;
      apt-get update;
      whoami;
      mkdir /artifacts/test;
      rmdir /artifacts/test;
    workingDir: $(workspaces.task-pvc.path)
  - name: kube-hunter
    image: aquasec/kube-hunter:0.5.0
    command: ["kube-hunter"]
    args: ["--pod"]
    workingDir: $(workspaces.task-pvc.path)
  workspaces:
  - name: task-pvc
    mountPath: /artifacts
